name: BlockMonsters
version: 1.0.0
main: com.jishunamatata.blockmonsters.BlockMonsters
api-version: 1.16

commands:
  blockmonsters:
    usage: /blockmonsters [reload | dumpblocks]
    description: General command for this plugin.
    
permissions:
  blockmonsters.reload:
    description: Allow a user to reload the config file.
  blockmonsters.dumpblocks:
    description: Allow a user to dump valid block names.